name: ci

on:
  pull_request

# Declare default permissions as read only.
permissions: read-all

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
    - name: Use Node.js
      uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a #v4.2.0
      with:
        node-version-file: '.nvmrc'
    - run: npm i
    - run: npm run test:ci
    - run: npm run lint
    - run: npm run build
    # - name: Coveralls
      # uses: coverallsapp/github-action@master
      # with:
        # github-token: ${{ secrets.GITHUB_TOKEN }}
